"""empty message

Revision ID: af7d2be182a2
Revises: 
Create Date: 2021-02-08 01:47:00.932213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af7d2be182a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userinfo', sa.Column('username', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'userinfo', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userinfo', type_='unique')
    op.drop_column('userinfo', 'username')
    # ### end Alembic commands ###
